paths:
  /auth/register:
    post:
      summary: Create a new user & login
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: User created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        422:
          description: Unprocessable entity. Wrong schema
  /auth/login:
    post:
      summary: Login
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: Sucessfull login.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        422:
          description: Unprocessable entity. Wrong schema
  /auth/status:
    get:
      summary: Returns the decoded token
      tags: [Auth]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                  iat:
                    type: number
                  exp:
                    type: number
        401:
          description: Unauthorized
        403:
          description: Forbiden
